### PR TITLE
feat: flatpak preparations

### PR DESCRIPTION
**Pull request by ludg1e**
This PR adds the required files for flatpak builds
The PR won't be marked as ready until all pending things are solved

Pending things (if you could answer the first three below @angryziber)

- [x] Does the "any" jar pkg support aarch64/arm64 linux? If yes, then we could package aarch64 as well, it's just a modification on the manifest
- [x] On the ipscan executable (script), what does the `--add-opens java.base/java.net=ALL-UNNAMED` option do exactly?
- [x] Which folders does the program create at the user's $HOME directory?
- [ ] Submit into flathub

I don't know if you'd like as well for each release a flatpak file to be built with GH Actions and published under releases on this repo, or only on Flathub.

Quote from the flatpak issue #147
> I can maintain the flatpak if you wish. As well the website could be updated adding the flathub link when the pkg is released.

### CODE REVIEW

**Comment by ludg1e** [comment]
I think I'll do as well another PR on gh-pages branch to update the website details

**Comment by angryziber** [comment]
Another question is the Java dependency: will the package bundle Java or somehow a system-wide version will be used?
If it is bundled, then it would be wise to build a smaller JRE using `jlink` as is done for Windows and MacOS builds.

**Comment by angryziber** [comment]
@ludg1e do I understand correctly that these files should actually go to a new repo under github.com/flatpak?
Is it possible to add a reference from flatpak to files in this repo?

**Comment by ludg1e** [comment]
> @ludg1e do I understand correctly that these files should actually go to a new repo under github.com/flatpak? Is it possible to add a reference from flatpak to files in this repo?

The manifest has been written so the files are fetched from the /ext folder of this repo (metainfo, svg icon, .desktop...) (basically this PR)
So, under the flathub GH organization only the manifest should be pushed into a new repo

**Comment by ludg1e** [comment]
The only thing that would need to be maintained is the url the manifest points to, so the version should be changed on each new release

**Comment by ludg1e** [comment]
Nevermind, all this is done automatically by the x-checker-data from the manifest that is as well checked by the flathub bot

**Comment by ludg1e** [comment]
Though now that I think you're right and to avoid redundant files it'd be better to use the original ones
I'll do a PR that pushes some modifications to the files

**Comment by ludg1e** [comment]
Continuation under #424

**Pull request closed without merging**
